<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h3 class="mb-2 pt-1"><b>Stage 3: Consultant Report</b></h3>
            <p><b>Status:</b> Final Design Output Report</p>
            <hr>
            <h2><b>Consultation Report</b></h2>
            
            <div class="row">
                <div class="col-md-6">
                    <h6><b>MSME Information</b></h6>
                    <input type="text" class="form-control mb-3" name="name" id="name" placeholder="Name" value="<?php echo $Data['name']; ?>" readonly />
                </div>
                <div class="col-md-6">
                    <h6><b>Product Information</b></h6>
                    <input type="text" class="form-control mb-3" name="product" id="product" placeholder="Name of Product" value="<?php echo $Data['ProductName']; ?>" readonly />
                    <input type="text" class="form-control mb-3" name="labelingformat" id="labelingformat" value="<?php echo $Data['labelingFormat']; ?>" readonly />
                    <input type="text" class="form-control mb-3" name="brandName" id="brandName" value="<?php echo $Data['brandName'] ?>" readonly />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h6>Product Identity Name: True Name/Nature of the Food (ex. salted Peanut, Dried Mango)</h6>
                    <input type="text" class="form-control mb-3" value="<?php echo $Data['ProductName'] ?>" readonly />
                </div>
            </div>
            <hr class="mb-4">
            <h2><b>Product Design Information</b></h2>
            <h6><b>Note:</b> This a report for the new final design output from the Consultant.</h6>
            <div class="row mt-4">
                <div class="col-md-12">
                    <h6 class="mb-2">Concept of Design</h6>
                    <textarea class="form-control mb-3" name="ConceptDesign" rows="7" readonly><?php echo $Data['ReportConceptDesign'] ?></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h6 class="mb-2">Size of the Product</h6>
                    <div class="form-check" style="margin-left:30px;">
                        <input class="form-check-input" type="radio" name="size" value="Small" <?php echo ($Data['ReportSize'] == 'small') ? 'checked' : ''; ?> required>
                        <label class="form-check-label" style="font-size: 15px;">Small</label>
                    </div>
                    <div class="form-check" style="margin-left:30px;">
                        <input class="form-check-input" type="radio" name="size" value="medium" <?php echo ($Data['ReportSize'] == 'medium') ? 'checked' : ''; ?> required>
                        <label class="form-check-label" style="font-size: 15px;">Medium</label>
                    </div>
                    <div class="form-check" style="margin-left:30px;">
                        <input class="form-check-input" type="radio" name="size" value="large" <?php echo ($Data['ReportSize'] == 'large') ? 'checked' : ''; ?> required>
                        <label class="form-check-label" style="font-size: 15px;">Large</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h6 class="mb-2">Notes or Other Comments:</h6>
                    <textarea class="form-control mb-3" name="Comment" rows="7" readonly><?php echo $Data['ReportComment'] ?></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h6 class="mb-2">Dominant Color used in the design:</h6>
                    <input class="form-control mb-3" type="text" name="DominantColor" id="tagline" value="<?php echo $Data['ReportDominantColor'] ?>" readonly />
                </div>
                <div class="col-md-6">
                    <h6 class="mb-2">Color used in the design:</h6>
                    <input type="text" id="displayColors" class="form-control mb-3" value="<?php echo $Data['ReportSelectedColor'] ?>" readonly>
                </div>
            </div>
            <table class="table">
                <!-- The table rows and cells will be generated by JavaScript -->
            </table>
            <hr>
            <div class="text-center">
                <h4><b>Final Output Design</b></h4>
                <img src="..\uploaded_img\<?php echo $Data['ReportDraftImage'] ?>" class="img-fluid" width="250px" height="250px">
            </div>
            <br>
            <div class="container mt-4">
                <form method="POST" action="review_Assessment.php">
                    <div class="mb-3 text-center">
                    <label for="decision">Note: Approve if the Final Design is Accepted. Reject if not satisfied.</label><br>
                    <input name="consultationID" type="hidden" value="<?php echo $Data['consultationID'] ?>">
                    <input name="room_id" type="hidden" value="<?php echo $Data['room_id'] ?>">
                    </div>
                    <div class="text-center">
                    <button type="submit" name="action" class="btn btn-primary text-white" value="approve">Approve</button>
                    <button type="submit" name="action" class="btn btn-danger text-white" value="delete">Reject</button>
                    </div>
                </form>
                <br>
            </div>
        </div>
    </div>
</div>